using Aiursoft.Apkg.Sdk.Models;

namespace Aiursoft.Apkg.Sdk.Services;

/// <summary>
/// Validates an .aosproj project file and returns a list of issues.
/// </summary>
public class AosprojLinter
{
    private readonly ConditionEvaluator _evaluator;

    public AosprojLinter(ConditionEvaluator evaluator)
    {
        _evaluator = evaluator;
    }

    public record LintIssue(Severity Level, string Message);
    public enum Severity { Warning, Error }

    public IReadOnlyList<LintIssue> Lint(AosprojProject project, string projectDir)
    {
        var issues = new List<LintIssue>();

        // Required fields
        RequireField(issues, project.PackageName, "PackageName");
        RequireField(issues, project.PackageVersion, "PackageVersion");
        RequireField(issues, project.PackageDescription, "PackageDescription");
        RequireField(issues, project.TargetSuites, "TargetSuites");

        // Strongly recommended fields (--all build mode requires them)
        if (string.IsNullOrWhiteSpace(project.TargetDistro))
            issues.Add(new LintIssue(Severity.Warning, "<TargetDistro> is not set. Required when using --all. Falling back to 'ubuntu'."));
        if (string.IsNullOrWhiteSpace(project.TargetArchitectures))
            issues.Add(new LintIssue(Severity.Warning, "<TargetArchitectures> is not set. Required when using --all."));

        // Maintainer or Authors
        if (string.IsNullOrWhiteSpace(project.Maintainer) && string.IsNullOrWhiteSpace(project.PackageAuthors))
            issues.Add(new LintIssue(Severity.Warning, "Neither <Maintainer> nor <PackageAuthors> is set."));

        // UpstreamSource: if deriving from a package, all upstream fields must be present
        if (project.HasUpstreamSource)
        {
            if (project.UpstreamUrls.Count == 0 || project.UpstreamUrls.All(u => string.IsNullOrWhiteSpace(u.Value)))
            {
                issues.Add(new LintIssue(Severity.Error, "UpstreamUrl (required when UpstreamPackage is set)"));
            }
            RequireField(issues, project.UpstreamDistro, "UpstreamDistro (required when UpstreamPackage is set)");
            RequireField(issues, project.UpstreamSuite, "UpstreamSuite (required when UpstreamPackage is set)");
            if (string.IsNullOrWhiteSpace(project.UpstreamComponent))
                issues.Add(new LintIssue(Severity.Warning, "<UpstreamComponent> is not set. Defaulting to 'main'."));
            if (string.IsNullOrWhiteSpace(project.UpstreamArch))
                issues.Add(new LintIssue(Severity.Warning, "<UpstreamArch> is not set. Defaulting to 'all'."));
        }

        // Package name must be lowercase with only letters, digits, and hyphens
        if (!string.IsNullOrWhiteSpace(project.PackageName) &&
            !System.Text.RegularExpressions.Regex.IsMatch(project.PackageName, @"^[a-z0-9][a-z0-9\-+.]*$"))
        {
            issues.Add(new LintIssue(Severity.Error,
                $"PackageName '{project.PackageName}' is not a valid Debian package name (lowercase, alphanumeric and hyphens only)."));
        }

        // Verify UpstreamSignedBy file exists (lint but don't hard-error — the file
        // could be generated by a PrebuildCommand before derivation happens).
        if (!string.IsNullOrWhiteSpace(project.UpstreamSignedBy))
            CheckSourceExists(issues, projectDir, project.UpstreamSignedBy, "UpstreamSignedBy");

        // Verify source files exist
        foreach (var item in project.IncludeFiles)
            CheckSourceExists(issues, projectDir, item.Source, "IncludeFile");

        foreach (var item in project.IncludeFolders)
            CheckSourceExists(issues, projectDir, item.Source, "IncludeFolder", isDirectory: true);

        foreach (var item in project.IncludeScripts)
            CheckSourceExists(issues, projectDir, item.Source, "IncludeScript");

        foreach (var item in project.ConfFiles)
            CheckSourceExists(issues, projectDir, item.Source, "ConfFile");

        foreach (var item in project.PostInstallScripts)
            CheckSourceExists(issues, projectDir, item.Source, "PostInstallScript");

        foreach (var item in project.PreRemoveScripts)
            CheckSourceExists(issues, projectDir, item.Source, "PreRemoveScript");

        foreach (var item in project.PreInstallScripts)
            CheckSourceExists(issues, projectDir, item.Source, "PreInstallScript");

        foreach (var item in project.PostRemoveScripts)
            CheckSourceExists(issues, projectDir, item.Source, "PostRemoveScript");

        foreach (var item in project.SystemdUnits)
            CheckSourceExists(issues, projectDir, item.Source, "SystemdUnit");

        LintAppStream(issues, project, projectDir);

        // Validate conditions are parseable
        var allConditions = project.Dependencies.Select(d => d.Condition)
            .Concat(project.IncludeFiles.Select(f => f.Condition))
            .Concat(project.IncludeFolders.Select(f => f.Condition))
            .Concat(project.IncludeScripts.Select(f => f.Condition))
            .Concat(project.ConfFiles.Select(f => f.Condition))
            .Concat(project.PostInstallScripts.Select(s => s.Condition))
            .Concat(project.PreRemoveScripts.Select(s => s.Condition))
            .Concat(project.PreInstallScripts.Select(s => s.Condition))
            .Concat(project.PostRemoveScripts.Select(s => s.Condition))
            .Concat(project.SystemdUnits.Select(u => u.Condition))
            .Concat(project.PrebuildCommands.Select(c => c.Condition))
            .Concat(project.DependencyCheckSources.Select(s => s.Condition))
            .Concat(project.AppStreamApplications.Select(a => a.Condition))
            .Concat(project.AppStreamScreenshots.Select(s => s.Condition));

        var dummyCtx = ConditionEvaluator.BuildContext("ubuntu", "jammy", "amd64",
            upstreamDistro: project.UpstreamDistro,
            upstreamSuite: project.UpstreamSuite,
            upstreamArch: project.UpstreamArch);
        foreach (var cond in allConditions.Where(c => !string.IsNullOrWhiteSpace(c)))
        {
            try { _evaluator.Evaluate(cond, dummyCtx); }
            catch (Exception ex)
            {
                issues.Add(new LintIssue(Severity.Error, $"Invalid condition '{cond}': {ex.Message}"));
            }
        }

        // Validate DependencyCheckSource entries
        foreach (var src in project.DependencyCheckSources)
        {
            if (string.IsNullOrWhiteSpace(src.Url))
                issues.Add(new LintIssue(Severity.Error, "<DependencyCheckSource> has empty Url."));
            if (string.IsNullOrWhiteSpace(src.SuiteMap))
                issues.Add(new LintIssue(Severity.Warning,
                    $"<DependencyCheckSource Url=\"{src.Url}\"> has no SuiteMap. Suite names will be used as-is."));
            if (!string.IsNullOrWhiteSpace(src.Condition))
            {
                try { _evaluator.Evaluate(src.Condition, dummyCtx); }
                catch (Exception ex)
                {
                    issues.Add(new LintIssue(Severity.Error,
                        $"DependencyCheckSource Invalid condition '{src.Condition}': {ex.Message}"));
                }
            }
        }

        // UpstreamSuiteMapping: validate format and consistency with TargetSuites
        if (!string.IsNullOrWhiteSpace(project.UpstreamSuiteMapping))
        {
            var suiteMap = project.GetUpstreamSuiteMap();
            var outputSuites = new HashSet<string>(project.SuiteList, StringComparer.OrdinalIgnoreCase);

            foreach (var pair in project.SuiteList)
            {
                if (!suiteMap.ContainsKey(pair))
                    issues.Add(new LintIssue(Severity.Warning,
                        $"<UpstreamSuiteMapping> has no entry for output suite '{pair}'."));
            }

            foreach (var (outputSuite, upstreamSuite) in suiteMap)
            {
                if (string.IsNullOrWhiteSpace(upstreamSuite))
                    issues.Add(new LintIssue(Severity.Error,
                        $"<UpstreamSuiteMapping> entry '{outputSuite}' has empty upstream suite."));
                if (!outputSuites.Contains(outputSuite))
                    issues.Add(new LintIssue(Severity.Warning,
                        $"<UpstreamSuiteMapping> entry '{outputSuite}' does not match any suite in <TargetSuites>."));
            }
        }
        if (!project.HasUpstreamSource &&
            !project.IncludeFiles.Any() &&
            !project.IncludeFolders.Any() &&
            !project.IncludeScripts.Any() &&
            !project.ConfFiles.Any() &&
            !project.AppStreamApplications.Any())
            issues.Add(new LintIssue(Severity.Warning, "No files declared to include. The package will be empty."));

        // Verify targets exist
        foreach (var item in project.IncludeFiles)
            RequireField(issues, item.Target, $"IncludeFile[@Include='{item.Source}'] Target");

        foreach (var item in project.IncludeFolders)
            RequireField(issues, item.Target, $"IncludeFolder[@Include='{item.Source}'] Target");

        foreach (var item in project.IncludeScripts)
            RequireField(issues, item.Target, $"IncludeScript[@Include='{item.Source}'] Target");

        foreach (var item in project.ConfFiles)
            RequireField(issues, item.Target, $"ConfFile[@Include='{item.Source}'] Target");

        return issues;
    }

    private static void LintAppStream(
        List<LintIssue> issues,
        AosprojProject project,
        string projectDir)
    {
        if (project.AppStreamApplications.Count == 0)
        {
            if (project.AppStreamScreenshots.Count > 0)
                issues.Add(new LintIssue(Severity.Error,
                    "<AppStreamScreenshot> requires at least one <AppStreamApplication>."));
            return;
        }

        if (string.IsNullOrWhiteSpace(project.AppStreamMetadataLicense))
            issues.Add(new LintIssue(Severity.Error, "<AppStreamMetadataLicense> must not be empty."));

        var appIds = new HashSet<string>(StringComparer.Ordinal);
        foreach (var application in project.AppStreamApplications)
        {
            if (!string.IsNullOrWhiteSpace(application.Condition))
                issues.Add(new LintIssue(Severity.Error,
                    "AppStreamApplication does not support Condition in manifest v3; application metadata is package-wide."));
            CheckRequiredFile(issues, projectDir, application.Source, "AppStreamApplication Include");
            CheckRequiredFile(issues, projectDir, application.Icon, "AppStreamApplication Icon");
            if (!string.IsNullOrWhiteSpace(application.Metainfo))
                CheckRequiredFile(issues, projectDir, application.Metainfo, "AppStreamApplication Metainfo");

            if (!application.Source.EndsWith(".desktop", StringComparison.OrdinalIgnoreCase))
                issues.Add(new LintIssue(Severity.Error,
                    $"AppStream application '{application.Source}' must reference a .desktop file."));

            var appId = AppStreamMetadataService.GetComponentId(application);
            if (!System.Text.RegularExpressions.Regex.IsMatch(appId, @"^[A-Za-z0-9][A-Za-z0-9._-]+$"))
                issues.Add(new LintIssue(Severity.Error, $"AppStream component ID '{appId}' is invalid."));
            if (!appIds.Add(appId))
                issues.Add(new LintIssue(Severity.Error, $"Duplicate AppStream component ID '{appId}'."));

            var desktopPath = Path.GetFullPath(Path.Combine(projectDir, application.Source));
            if (File.Exists(desktopPath))
                LintDesktopEntry(issues, desktopPath, application, appId);

            if (!string.IsNullOrWhiteSpace(application.Metainfo))
                LintMetainfo(issues, Path.GetFullPath(Path.Combine(projectDir, application.Metainfo)), appId);
        }

        var screenshotGroups = new Dictionary<string, List<AppStreamScreenshotItem>>(StringComparer.Ordinal);
        foreach (var screenshot in project.AppStreamScreenshots)
        {
            if (!string.IsNullOrWhiteSpace(screenshot.Condition))
                issues.Add(new LintIssue(Severity.Error,
                    "AppStreamScreenshot does not support Condition in manifest v3; screenshot metadata is package-wide."));
            var appId = screenshot.AppId;
            if (string.IsNullOrWhiteSpace(appId))
            {
                if (appIds.Count != 1)
                {
                    issues.Add(new LintIssue(Severity.Error,
                        $"AppStream screenshot '{screenshot.Source}' must set AppId because this package declares multiple applications."));
                    continue;
                }
                appId = appIds.Single();
            }
            else if (!appIds.Contains(appId))
            {
                issues.Add(new LintIssue(Severity.Error,
                    $"AppStream screenshot '{screenshot.Source}' references unknown AppId '{appId}'."));
                continue;
            }

            if (!screenshotGroups.TryGetValue(appId, out var screenshots))
                screenshotGroups[appId] = screenshots = [];
            screenshots.Add(screenshot);

            var screenshotPath = Path.GetFullPath(Path.Combine(projectDir, screenshot.Source));
            if (!File.Exists(screenshotPath))
            {
                issues.Add(new LintIssue(Severity.Error,
                    $"AppStream screenshot not found: {screenshotPath}"));
                continue;
            }
            if (new FileInfo(screenshotPath).Length > 14 * 1024 * 1024)
                issues.Add(new LintIssue(Severity.Error,
                    $"AppStream screenshot '{screenshot.Source}' exceeds the 14 MiB limit."));
            try
            {
                var metadata = ImageMetadataReader.Read(screenshotPath);
                if (metadata.Width <= 0 || metadata.Height <= 0)
                    issues.Add(new LintIssue(Severity.Error,
                        $"AppStream screenshot '{screenshot.Source}' has invalid dimensions."));
                else
                {
                    if (metadata.Width < 620)
                        issues.Add(new LintIssue(Severity.Warning,
                            $"AppStream screenshot '{screenshot.Source}' is only {metadata.Width}px wide; 620px or wider is recommended."));
                    var aspectRatio = (double)metadata.Width / metadata.Height;
                    if (Math.Abs(aspectRatio - 16.0 / 9.0) > 0.08)
                        issues.Add(new LintIssue(Severity.Warning,
                            $"AppStream screenshot '{screenshot.Source}' is {metadata.Width}x{metadata.Height}; a 16:9 image is recommended."));
                }
            }
            catch (Exception ex) when (ex is IOException or InvalidDataException)
            {
                issues.Add(new LintIssue(Severity.Error,
                    $"AppStream screenshot '{screenshot.Source}' is invalid: {ex.Message}"));
            }

            if (screenshot.Caption.Length > 100)
                issues.Add(new LintIssue(Severity.Warning,
                    $"AppStream screenshot '{screenshot.Source}' has a caption longer than 100 characters."));
        }

        foreach (var (appId, screenshots) in screenshotGroups)
        {
            if (screenshots.Count > 10)
                issues.Add(new LintIssue(Severity.Error,
                    $"AppStream application '{appId}' has {screenshots.Count} screenshots; at most 10 are supported."));
            if (screenshots.Count(s => s.Default) > 1)
                issues.Add(new LintIssue(Severity.Error,
                    $"AppStream application '{appId}' has more than one default screenshot."));
        }
    }

    private static void LintDesktopEntry(
        List<LintIssue> issues,
        string desktopPath,
        AppStreamApplicationItem application,
        string appId)
    {
        var desktop = AppStreamMetadataService.ReadDesktopEntryAsync(desktopPath).GetAwaiter().GetResult();
        if (!desktop.TryGetValue("Type", out var type) || type != "Application")
            issues.Add(new LintIssue(Severity.Error,
                $"AppStream desktop entry '{application.Source}' must contain Type=Application."));
        if (!desktop.ContainsKey("Name"))
            issues.Add(new LintIssue(Severity.Error,
                $"AppStream desktop entry '{application.Source}' must contain Name=."));
        if (!desktop.ContainsKey("Comment"))
            issues.Add(new LintIssue(Severity.Warning,
                $"AppStream desktop entry '{application.Source}' has no Comment=; PackageDescription will be used."));
        if (desktop.TryGetValue("Icon", out var desktopIcon))
        {
            var declaredIcon = Path.GetFileNameWithoutExtension(application.Icon);
            if (!string.Equals(desktopIcon, declaredIcon, StringComparison.Ordinal) &&
                !string.Equals(Path.GetFileNameWithoutExtension(desktopIcon), declaredIcon, StringComparison.Ordinal))
                issues.Add(new LintIssue(Severity.Error,
                    $"Desktop Icon='{desktopIcon}' does not match AppStreamApplication Icon='{application.Icon}' for '{appId}'."));
        }
    }

    private static void LintMetainfo(List<LintIssue> issues, string path, string expectedId)
    {
        if (!File.Exists(path))
            return;
        try
        {
            var document = System.Xml.Linq.XDocument.Load(path);
            var root = document.Root;
            var id = root?.Elements().FirstOrDefault(e => e.Name.LocalName == "id")?.Value;
            if (root?.Name.LocalName != "component")
                issues.Add(new LintIssue(Severity.Error, $"AppStream metainfo '{path}' must have a <component> root."));
            if (!string.Equals(id, expectedId, StringComparison.Ordinal))
                issues.Add(new LintIssue(Severity.Error,
                    $"AppStream metainfo ID '{id}' does not match desktop component ID '{expectedId}'."));
        }
        catch (Exception ex) when (ex is IOException or System.Xml.XmlException)
        {
            issues.Add(new LintIssue(Severity.Error, $"AppStream metainfo '{path}' is invalid XML: {ex.Message}"));
        }
    }

    private static void CheckRequiredFile(
        List<LintIssue> issues,
        string projectDir,
        string source,
        string field)
    {
        if (string.IsNullOrWhiteSpace(source))
        {
            issues.Add(new LintIssue(Severity.Error, $"<{field}> is required but not set."));
            return;
        }
        var path = Path.GetFullPath(Path.Combine(projectDir, source));
        if (!File.Exists(path))
            issues.Add(new LintIssue(Severity.Warning, $"<{field}> path not found: {path}"));
    }

    private static void RequireField(List<LintIssue> issues, string value, string fieldName)
    {
        if (string.IsNullOrWhiteSpace(value))
            issues.Add(new LintIssue(Severity.Error, $"<{fieldName}> is required but not set."));
    }

    private static void CheckSourceExists(List<LintIssue> issues, string projectDir,
        string source, string itemType, bool isDirectory = false)
    {
        if (string.IsNullOrWhiteSpace(source))
        {
            issues.Add(new LintIssue(Severity.Error, $"<{itemType}> has empty Source attribute."));
            return;
        }

        var fullPath = Path.GetFullPath(Path.Combine(projectDir, source));
        var exists = isDirectory ? Directory.Exists(fullPath) : File.Exists(fullPath);
        if (!exists)
        {
            issues.Add(new LintIssue(Severity.Warning,
                $"<{itemType} Source=\"{source}\" /> — source path not found: {fullPath}"));
        }
    }
}
